# Generated by Django 5.2.9 on 2025-12-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('category', models.IntegerField()),
                ('completions', models.JSONField(default=list)),
                ('duration', models.IntegerField()),
                ('days', models.JSONField(default=list)),
            ],
        ),
    ]
