# Generated by Django 5.2.9 on 2025-12-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
