# Generated by Django 5.2.9 on 2025-12-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_api', '0002_rename_completion_habit_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='end_date',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='start_date',
        ),
        migrations.AddField(
            model_name='habit',
            name='completion',
            field=models.JSONField(default=list),
        ),
    ]
