# Generated by Django 5.2.9 on 2025-12-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_api', '0003_rename_end_date_habit_start_remove_habit_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='days',
            field=models.JSONField(default=list),
        ),
    ]
