# Generated by Django 5.2.9 on 2025-12-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits_api', '0004_habit_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='completion',
            new_name='completions',
        ),
    ]
